source 'https://api.berkshelf.com'

cookbook 'build-essential', '~> 2.0.4'
cookbook 'apt', '~> 2.4.0'
cookbook 'git', '~> 4.0.2'
cookbook 'nodejs', '~> 2.0.0'
cookbook 'nginx', '~> 2.7.4'
cookbook 'mysql', '= 5.5.3'
cookbook 'user', '~> 0.3.0'
cookbook 'openssh', '~> 1.3.4'
cookbook 'slack-harvest-middleman', path: './build/chef/cookbooks/slack-harvest-middleman'